-- MySQL Script generated by MySQL Workbench
-- Tue Jan 21 00:21:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema subway
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema subway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `subway` DEFAULT CHARACTER SET utf8 ;
USE `subway` ;

-- -----------------------------------------------------
-- Table `subway`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`station` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`worker` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  `hourly_wage` DECIMAL UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`line` (
  `name` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`driver` (
  `worker_id` BIGINT UNSIGNED NOT NULL,
  `line_name` MEDIUMTEXT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`worker_id` ASC) VISIBLE,
  INDEX `name_idx` (`line_name` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`worker_id`)
    REFERENCES `subway`.`worker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `name`
    FOREIGN KEY (`line_name`)
    REFERENCES `subway`.`line` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`zone` (
  `name` MEDIUMTEXT NOT NULL,
  `base_fare_one_minute` DECIMAL UNSIGNED NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`route_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`route_section` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `departure_station_id` BIGINT UNSIGNED NOT NULL,
  `destination_station_id` BIGINT UNSIGNED NOT NULL,
  `minutes` BIGINT UNSIGNED NOT NULL,
  `zone_name` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `name_idx` (`zone_name` ASC) VISIBLE,
  INDEX `id_idx` (`departure_station_id` ASC) VISIBLE,
  INDEX `id_idx1` (`destination_station_id` ASC) VISIBLE,
  CONSTRAINT `name`
    FOREIGN KEY (`zone_name`)
    REFERENCES `subway`.`zone` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`departure_station_id`)
    REFERENCES `subway`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`destination_station_id`)
    REFERENCES `subway`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`discount` (
  `name` MEDIUMTEXT NOT NULL,
  `reduction_percentage` DECIMAL UNSIGNED NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`transit_pass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`transit_pass` (
  `name` MEDIUMTEXT NOT NULL,
  `outermost_zone_name` MEDIUMTEXT NOT NULL,
  `number_of_days` BIGINT UNSIGNED NOT NULL,
  `price` DECIMAL UNSIGNED NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `name_idx` (`outermost_zone_name` ASC) VISIBLE,
  CONSTRAINT `name`
    FOREIGN KEY (`outermost_zone_name`)
    REFERENCES `subway`.`zone` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`passenger` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` MEDIUMTEXT NOT NULL,
  `discount_name` MEDIUMTEXT NULL,
  `credit` DECIMAL UNSIGNED NOT NULL,
  `transit_pass_name` MEDIUMTEXT NULL,
  `pass_validity_starting_day` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `name_idx` (`discount_name` ASC) VISIBLE,
  INDEX `name_idx1` (`transit_pass_name` ASC) VISIBLE,
  CONSTRAINT `name`
    FOREIGN KEY (`discount_name`)
    REFERENCES `subway`.`discount` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `name`
    FOREIGN KEY (`transit_pass_name`)
    REFERENCES `subway`.`transit_pass` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`line_has_route_section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`line_has_route_section` (
  `line_name` MEDIUMTEXT NOT NULL,
  `route_section_id` BIGINT UNSIGNED NOT NULL,
  `section_no` BIGINT UNSIGNED NOT NULL,
  INDEX `id_idx` (`route_section_id` ASC) VISIBLE,
  CONSTRAINT `name`
    FOREIGN KEY (`line_name`)
    REFERENCES `subway`.`line` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`route_section_id`)
    REFERENCES `subway`.`route_section` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subway`.`station_worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subway`.`station_worker` (
  `worker_id` BIGINT UNSIGNED NOT NULL,
  `station_id` BIGINT UNSIGNED NOT NULL,
  UNIQUE INDEX `worker_id_UNIQUE` (`worker_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`worker_id`)
    REFERENCES `subway`.`worker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id`
    FOREIGN KEY (`station_id`)
    REFERENCES `subway`.`station` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
